# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "aesni_intel" "cryptd"];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "v4l2loopback" ];
  boot.extraModulePackages = [ pkgs.linuxPackages_latest.v4l2loopback ];
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
  hardware.enableRedistributableFirmware = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/43f8fb10-f299-4c8e-ba37-36734291dd59";
      fsType = "btrfs";
      options = [ "subvol=nixos" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/43f8fb10-f299-4c8e-ba37-36734291dd59";
      fsType = "btrfs";
      options = [ "subvol=nixos/home" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/01825380-edea-4ecf-ba90-b3edfc199fc0";
  boot.initrd.luks.devices."swap".device = "/dev/disk/by-uuid/600465d8-3f5f-48be-b5d6-f009811300d3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/743B-1381";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a0c4bd8f-7afa-4a22-975d-919c0f627141"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
