# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" "aesni_intel" "cryptd" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "v4l2loopback" ];
  boot.extraModulePackages = [ pkgs.linuxPackages_5_16.v4l2loopback ];
  boot.extraModprobeConfig = ''
      options v4l2loopback exclusive_caps=1 video_nr=9 card_label="OBS Virtual Output"
    '';
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1a997aa3-9ee5-487b-bc03-e6754bb979a3";
      fsType = "btrfs";
      options = [ "subvol=root" "noatime" "compress=zstd:3" "space_cache=v2" "autodefrag" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1a997aa3-9ee5-487b-bc03-e6754bb979a3";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "compress=zstd:3" "space_cache=v2" "autodefrag" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1a997aa3-9ee5-487b-bc03-e6754bb979a3";
      fsType = "btrfs";
      options = [ "subvol=home" "noatime" "compress=zstd:3" "space_cache=v2" "autodefrag" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/f7e04385-e734-4331-8f80-f15a578a33b4";
  boot.initrd.luks.devices."swap".device = "/dev/disk/by-uuid/710c288d-ed1e-4d65-bf77-726e6153edd9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/52FC-EBC9";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4db3a053-e37b-4337-8c9c-cb77c1d63bcb"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
  hardware.ckb-next.enable = true;

  # Enable nvidia vgpu
  # hardware.nvidia.vgpu.enable = true; # Enable NVIDIA KVM vGPU + GRID driver
  # hardware.nvidia.vgpu.unlock.enable = true; # Unlock vGPU functionality on consumer cards using DualCoder/vgpu_unlock project.

  # Enable nvidia modesetting
  hardware.nvidia.modesetting.enable = true;

  # My usb sound card is 44100Hz
  # This fixes crackling when adjusting playback volume on youtube
  # hardware.pulseaudio.daemon.config = {
  #   default-sample-rate = "44100";
  #   avoid-resampling = "true";
  #   # configFile = pkgs.runCommand "default.pa" {} ''
  #   #   sed 's/module-udev-detect$/module-udev-detect tsched=0/' \
  #   #     ${pkgs.pulseaudio}/etc/pulse/default.pa > $out
  #   # '';
  # };

  # Make steam detect my DualShock 4 "Slim" controller (and others for reference)
  services.udev.extraRules = ''
    # Unprivileged uinput
    KERNEL=="uinput", MODE="0666"
    # DualShock 4 over USB hidraw
    KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="05c4", MODE="0666"
    # DualShock 4 wireless adapter over USB hidraw
    KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0ba0", MODE="0666"
    # DualShock 4 Slim over USB hidraw
    KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="09cc", MODE="0666"
    # DualShock 4 over bluetooth hidraw
    KERNEL=="hidraw*", KERNELS=="*054C:05C4*", MODE="0666"
    # DualShock 4 Slim over bluetooth hidraw
    KERNEL=="hidraw*", KERNELS=="*054C:09CC*", MODE="0666"
  '';
}
